# Rename back to .travis.yml to use again, currently disabled

language: python
python:
  # - 3.4
  # - 3.5
  # - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
before_install:
  - sudo apt-get install -y python-smbus
  - sudo apt-get install -y i2c-tools
install:
  - pip install unittest2
  - pip install pyyaml
  - pip install adafruit_pca9685
  - pip install flask
  - pip install flask_bootstrap
  - pip install flask_sqlalchemy
  - pip install flask_wtf
  - pip install pathlib
  - pip install smars-library
script: python smarslab_test_suite.py
